# Generated by Django 2.2.1 on 2019-05-22 15:06

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=500)),
                ('atype', models.CharField(max_length=500)),
                ('picUrl', models.CharField(max_length=500)),
                ('lettNum', models.IntegerField()),
                ('publish_time', models.CharField(max_length=500)),
                ('cover_rate', models.CharField(max_length=500)),
                ('date', models.DateField(default=datetime.datetime(2019, 5, 22, 15, 6, 2, 953846, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('uid', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('openid', models.CharField(max_length=500)),
                ('dict', models.CharField(max_length=500, null=True)),
                ('cover_rate', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='vocabulary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_rate', models.CharField(max_length=500, null=True)),
                ('date', models.DateField(default=datetime.datetime(2019, 5, 22, 15, 6, 2, 954844, tzinfo=utc))),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.user')),
            ],
        ),
        migrations.CreateModel(
            name='collectArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2019, 5, 22, 15, 6, 2, 955844, tzinfo=utc))),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.user')),
            ],
        ),
    ]
