# Generated by Django 2.2.1 on 2019-05-17 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=500)),
                ('atype', models.CharField(max_length=500)),
                ('picUrl', models.CharField(max_length=500)),
                ('lettNum', models.IntegerField()),
                ('publish_time', models.CharField(max_length=500)),
                ('cover_rate', models.CharField(max_length=500)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('openid', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('dict', models.CharField(max_length=500, null=True)),
                ('cover_rate', models.CharField(max_length=500, null=True)),
                ('collectArticle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.article')),
            ],
        ),
    ]
