# Generated by Django 2.2.1 on 2019-05-23 08:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 5, 23, 8, 4, 49, 758803, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='collectarticle',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 5, 23, 8, 4, 49, 759802, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 5, 23, 8, 4, 49, 758803, tzinfo=utc)),
        ),
    ]
