# Generated by Django 2.2.1 on 2019-05-23 08:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190523_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 5, 23, 8, 24, 22, 15594, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='collectarticle',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 5, 23, 8, 24, 22, 16591, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 5, 23, 8, 24, 22, 16591, tzinfo=utc)),
        ),
    ]
