# Generated by Django 2.2.1 on 2019-05-30 07:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20190523_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 5, 30, 7, 41, 10, 194214, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='collectarticle',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 5, 30, 7, 41, 10, 197214, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 5, 30, 7, 41, 10, 195214, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='testHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_rate', models.CharField(max_length=500)),
                ('date', models.DateField(default=datetime.datetime(2019, 5, 30, 7, 41, 10, 198211, tzinfo=utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.user')),
            ],
        ),
    ]
